name: FateHub
main: me.Hackusate_PvP.FateHub.Main
version: 1.4
author: Hackusate_PvP
softdepend:
  - EzQueueSpigot
  - Vault
commands:
  creative:
    aliases: [gmc]
    description: Switch gamemodes easily.
  cosmetic:
    description: Opens the cosmetic gui
  survival:
    aliases: [gms]
    description: Switch gamemodes easily.
  register:
    description: Protect your account safely on the server.
  fatehub:
    description: Base command.
  info:
    description: View the info of a player.
  login:
    description: Login into your account.
  status:
    description: Change the status of servers.
  settings:
    description: Edit your settings
  resetinventory:
    aliases: [reseti]
    description: Reset your hotbar.
  togglescoreboard:
    aliases: [ts, toggls]
    description: Toggle visibility of your scoreboard
  toggleplayers:
    aliases: [togglep, tpl]
    description: Toggle visibility of all other players