Tablist:
  Name: "&9&lTablist"
  Material: "PAINTING"
  Lore:
  - ""
  - "&b&lTab: %tabstatus%"
  - ""
  Enchantment:
    Type: "DAMAGE_ALL"
    Level: 2
Scoreboard:
  Name: "&9&lScoreboard"
  Material: "ITEM_FRAME"
  Lore:
  - ""
  - "&b&lScoreboard: %sstatus%"
  - ""
  Enchantment:
    Type: "DAMAGE_ALL"
    Level: 2
Vanish:
  Name: "&9&lVanish"
  Material: "POTION"
  Lore:
  - ""
  - "&b&lVisibility: %vanstatus%"
  - ""
  Enchantment:
    Type: "DAMAGE_ALL"
    Level: 2
DJ:
  Name: "&9&lDoubleJump"
  Material: "IRON_BOOTS"
  Lore:
  - ""
  - "&b&lDoubleJump: %vanstatus%"
  - ""
  Enchantment:
    Type: "DAMAGE_ALL"
    Level: 2
Chat:
  Name: "&9&lDoubleJump"
  Material: "PAPER"
  Lore:
  - ""
  - "&b&lChatting: %vanstatus%"
  - ""
  Enchantment:
    Type: "DAMAGE_ALL"
    Level: 2